# config.yaml


# Database information, input your credentials here before running in production!
database:
  user: root
  password: your_db_password
  host: your_db_host
  port: your_db_port
  name: your_db_name
